FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Load environment variables
COPY .env .env

# Build the application
RUN npm run build

EXPOSE 3000

# Start the application
CMD ["npm", "start"]