version: "3.8"

services:
  django:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.prod
    container_name: django-backend
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - logs_volume:/app/logs
      - ./backend/logs:/app/logs
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=django,${DOMAIN},www.${DOMAIN}
      - CSRF_TRUSTED_ORIGINS=https://${DOMAIN},https://www.${DOMAIN}
    networks:
      - app-network

  nextjs:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    container_name: next-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: sh -c "npm install && npm run build && npm run start"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=https://${DOMAIN}/api
      - NEXT_PUBLIC_ALLOWED_ORIGIN=https://${DOMAIN}

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      - letsencrypt-etc:/etc/letsencrypt
      - letsencrypt-www:/var/lib/letsencrypt
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextjs
      - django
    networks:
      - app-network
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt-etc:/etc/letsencrypt
      - letsencrypt-www:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: >
      certonly
      --webroot
      -w /var/lib/letsencrypt
      --email ${SSL_EMAIL}
      --agree-tos
      --no-eff-email
      --force-renewal
      -d mn-developer.com
      -d www.mn-developer.com
    restart: "no"

  certbot-renew:
    image: certbot/certbot
    volumes:
      - letsencrypt-etc:/etc/letsencrypt
      - letsencrypt-www:/var/lib/letsencrypt
    entrypoint: sh
    command: >
      -c '
      echo "0 0,12 * * * certbot renew --quiet" > /etc/crontabs/root;
      crond -f
      '
    restart: always

volumes:
  static_volume:
  letsencrypt-etc:
  letsencrypt-www:
  media_volume:
  logs_volume:

networks:
  app-network:
    driver: bridge
